spring:
  thymeleaf:
    templateResolverOrder: 1
  application:
    name: ff4j-sandbox
  jackson:
    default-property-inclusion: non_null
    
health:
  config:
    enabled: false

server:
  port: 8086

logging:
  level:
    root: error